# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/portscan

FORMS += scandlg.ui \
         optdlg.ui 
HEADERS += portscan.h \
           opt.h \
           myvar.h 
SOURCES += main.cpp \
           portscan.cpp \
           opt.cpp 
TEMPLATE = app
CONFIG += release \
warn_on \
thread \
qt
TARGET = ../bin/portscan
